version: "3.9"

services:
  # === PostgreSQL 17 ===
  postgres:
    image: postgres:17
    container_name: moraisdabet_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - net

# === LocalStack (para SQS) ===
  localstack:
    image: localstack/localstack:latest
    container_name: moraisdabet_sqs
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "4566:4566"   # endpoint principal dos servi√ßos
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - net


volumes:
  postgres_data:

networks:
  net:
    driver: bridge
